# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee2dd5f020c04f1094a2aaf1296a80abcf87a9a945a8c3bccc43fc3ba31416c78686f647ed25af6b8fe51ce2d40e9907efb6debf8e6b7c9db4f1e799b1d8799c

test:
  secret_key_base: 96975b4f7b64d7e0aef6f2298e1f7067cdfb9afffeaf03544411107e001f7845ef392d9c047da61b7354a2185c996c269a808c099f4cf5c1186d9c4a7c20838a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
